### ISSUE TITLE
Add support for password authentication against CrateDB nodes

### ISSUE THREAD

**Issue by chaudum** [mfussenegger/cr8#213]
Commands like `run-spec`, `insert-fake-data`, etc should also work against CrateDB nodes that require authentication.

I am happy to contribute the feature. :)

**Comment by mfussenegger** [comment]
@chaudum happy to accept a PR. Do you a suggestion for the API? I wonder if we should encode that in the `uri`. 

In any case it should be done in a way that it could also work if postgres protocol support is added (see also https://github.com/mfussenegger/cr8/commit/070bc508d7ffa56a8574a7687a28c65b87b096e1#diff-2345aa41bb2a19cab06cf12da70c7062R132)

**Comment by chaudum** [comment]
Encoding username/password in the URI is a good idea.
There are two options:

1) jdbc style: as parameter after the schema, e.g. `crate://example.com:4200/doc?username=foo&password=secret`
2) http style: as username password before hostname, e.g. `crate://foo:secret@example.com:4200/doc`

I tend more towards the latter. What do you think?

**Comment by mfussenegger** [comment]
I'm in favour of 2)

**Comment by chaudum** [comment]
```console
$ cr8 insert-fake-data --hosts http://user:pass@localhost:4200 ...
```
works already

**Comment by mfussenegger** [comment]
@chaudum want to create a PR to document this?

**Comment by mfussenegger** [comment]
Closing this for now, happy to take a PR that extends the documentation.
