### ISSUE TITLE
Getting error when using list of jsons 

### ISSUE THREAD

**Issue by MarkRatFelt** [mfussenegger/cr8#326]
**Describe the bug**
If I have a file with a list of JSONs, then I get an AttributeError: 

`AttributeError: 'list' object has no attribute 'items'`

**To Reproduce**

1- some panda dataset
2- data_set.to_json('data.json', orient='records')

```
cr8 insert-json --table somedb --host somehost -c 50  -b 2500 -i data.json
```

**Expected behavior**

**cr8 Version: (`cr8 --version`)**

**Additional context**

Attached the file
[data.json.zip](https://github.com/mfussenegger/cr8/files/4988102/data.json.zip)

**Comment by mfussenegger** [comment]
Thank you for the report.

This will be fixed with https://github.com/mfussenegger/cr8/pull/328

In the meantime, as a workaround you could pre-process the data like this:

```
cat data.json| jq -c -s  '.[] | .[]' | cr8 insert-json --table tbl --hosts localhost:4200
```

So far the following input formats were supported:

    1 JSON object per line is supported:

        {"name": "n1"}
        {"name": "n2"}

    Or 1 JSON object:

        {
            "name": "n1"
        }

    Or a list of JSON objects:

        [
            {"name": "n1"},
            {"name": "n2"},
        ]
